name: JavaScript Linter

on:
  push:
    branches:
      - main # À adapter selon vos besoins

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Version de Node.js à utiliser

      - name: Install JSLint
        run: npm install -g jslint # Installer JSLint globalement

      - name: Run JSLint
        run: |
          jslint your_file.js || exit 1 # Exécuter JSLint et sortir avec le code 1 s'il y a des erreurs

      - name: Verify linting results
        run: exit 0 # Cette étape est uniquement pour clarifier que la vérification s'est terminée avec succès

      - name: Stop workflow if errors were found
        if: ${{ failure() }}
        run: echo "JSLint found errors. Cancelling the workflow." && exit 1
