name: JSLint Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install JSLint
        run: npm install -g jslint

      - name: Run JSLint
        run: |
          jslint *.js || exit 1
